import {
  BASE_MAP_DOT_COUNT,
  COUNTRY_NAMES,
  MANUAL_MAPPINGS,
} from './mappings';

export const CONTINENT_OPTIONS = [
  'Asia',
  'Africa',
  'North America',
  'South America',
  'Europe',
  'Australia & Oceania',
] as const;

export type ContinentName = (typeof CONTINENT_OPTIONS)[number];

const CONTINENT_COUNTRY_SOURCE = {
  'North America': [
    'Anguilla',
    'Antigua and Barbuda',
    'Aruba',
    'Bajo Nuevo Bank (Petrel Is.)',
    'Barbados',
    'Belize',
    'Bermuda',
    'British Virgin Islands',
    'Canada',
    'Cayman Islands',
    'Clipperton Island',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Dominica',
    'Dominican Republic',
    'El Salvador',
    'Greenland',
    'Grenada',
    'Guatemala',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Mexico',
    'Montserrat',
    'Nicaragua',
    'Panama',
    'Puerto Rico',
    'Saint Barthelemy',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Serranilla Bank',
    'Sint Maarten',
    'The Bahamas',
    'Trinidad and Tobago',
    'Turks and Caicos Islands',
    'US Naval Base Guantanamo Bay',
    'United States Minor Outlying Islands',
    'United States Virgin Islands',
    'United States of America',
  ],
  'South America': [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Brazilian Island',
    'Chile',
    'Colombia',
    'Ecuador',
    'Falkland Islands',
    'Guyana',
    'Paraguay',
    'Peru',
    'South Georgia and the Islands',
    'Southern Patagonian Ice Field',
    'Suriname',
    'Uruguay',
    'Venezuela',
  ],
  Europe: [
    'Aland',
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Denmark',
    'Estonia',
    'Faroe Islands',
    'Finland',
    'France',
    'Germany',
    'Gibraltar',
    'Greece',
    'Guernsey',
    'Hungary',
    'Iceland',
    'Ireland',
    'Isle of Man',
    'Italy',
    'Jersey',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Republic of Serbia',
    'Romania',
    'San Marino',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom',
    'Vatican',
  ],
  Africa: [
    'Algeria',
    'Angola',
    'Benin',
    'Bir Tawil',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Democratic Republic of the Congo',
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'eSwatini',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Ivory Coast',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Republic of the Congo',
    'Rwanda',
    'Saint Helena',
    'São Tomé and Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'Somaliland',
    'South Africa',
    'South Sudan',
    'Sudan',
    'Togo',
    'Tunisia',
    'Uganda',
    'United Republic of Tanzania',
    'Western Sahara',
    'Zambia',
    'Zimbabwe',
  ],
  Asia: [
    'Afghanistan',
    'Akrotiri Sovereign Base Area',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Baykonur Cosmodrome',
    'Bhutan',
    'British Indian Ocean Territory',
    'Brunei',
    'Cambodia',
    'China',
    'Cyprus',
    'Cyprus No Mans Area',
    'Dhekelia Sovereign Base Area',
    'Timor-Leste',
    'Georgia',
    'Hong Kong S.A.R.',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Macao S.A.R',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'North Korea',
    'Northern Cyprus',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Scarborough Reef',
    'Siachen Glacier',
    'Singapore',
    'South Korea',
    'Spratly Islands',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
    'Yemen',
  ],
  'Australia & Oceania': [
    'American Samoa',
    'Ashmore and Cartier Islands',
    'Australia',
    'Cook Islands',
    'Coral Sea Islands',
    'Federated States of Micronesia',
    'Fiji',
    'French Polynesia',
    'Guam',
    'Kiribati',
    'Marshall Islands',
    'Nauru',
    'New Caledonia',
    'New Zealand',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands',
    'Palau',
    'Papua New Guinea',
    'Pitcairn Islands',
    'Samoa',
    'Solomon Islands',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
    'Wallis and Futuna',
  ],
} as const satisfies Record<ContinentName, readonly string[]>;

export const CONTINENT_COUNTRY_MAP: Record<ContinentName, string[]> = CONTINENT_OPTIONS.reduce(
  (acc, continent) => ({
    ...acc,
    [continent]: [...CONTINENT_COUNTRY_SOURCE[continent]],
  }),
  {} as Record<ContinentName, string[]>,
);

// Country footprints intentionally share a few coarse artwork dots. Continent
// mode needs one visual owner per visible dot so borders do not produce holes
// or light up a neighboring landmass.
const VISUAL_CONTINENT_DOT_OWNERS: Record<number, ContinentName> = {
  // Iceland sits beside Greenland on the compressed North Atlantic grid.
  576: 'Europe',
  593: 'Europe',
  642: 'Europe',
  678: 'Europe',
  689: 'Europe',
  745: 'Europe',
  794: 'Europe',

  // These Baltic dots were incorrectly inherited by Mauritania and Russia.
  1017: 'Europe',
  1018: 'Europe',
  1153: 'Europe',
  1248: 'Europe',

  // Complete small gaps without changing their country-level mappings.
  1658: 'Asia',
  2077: 'North America',
  2198: 'South America',
  2453: 'Australia & Oceania',
  2456: 'Australia & Oceania',

  // Shared country dots are assigned to the landmass they visually touch.
  2064: 'South America',
  2412: 'Australia & Oceania',
};

const createContinentDotMap = (): Record<ContinentName, number[]> => {
  const dotSets = CONTINENT_OPTIONS.reduce(
    (acc, continent) => ({ ...acc, [continent]: new Set<number>() }),
    {} as Record<ContinentName, Set<number>>,
  );

  CONTINENT_OPTIONS.forEach((continent) => {
    CONTINENT_COUNTRY_MAP[continent].forEach((countryName) => {
      MANUAL_MAPPINGS[countryName]?.forEach((dotIndex) => {
        if (dotIndex < BASE_MAP_DOT_COUNT) dotSets[continent].add(dotIndex);
      });
    });
  });

  Object.entries(VISUAL_CONTINENT_DOT_OWNERS).forEach(([rawDotIndex, owner]) => {
    const dotIndex = Number(rawDotIndex);
    CONTINENT_OPTIONS.forEach((continent) => dotSets[continent].delete(dotIndex));
    dotSets[owner].add(dotIndex);
  });

  return CONTINENT_OPTIONS.reduce(
    (acc, continent) => ({
      ...acc,
      [continent]: [...dotSets[continent]].sort((a, b) => a - b),
    }),
    {} as Record<ContinentName, number[]>,
  );
};

export const CONTINENT_DOT_MAP = createContinentDotMap();

export const UNASSIGNED_CONTINENT_COUNTRIES = COUNTRY_NAMES.filter(
  (countryName) =>
    countryName !== 'Antarctica' &&
    !(Object.values(CONTINENT_COUNTRY_SOURCE) as readonly (readonly string[])[])
      .some((countries) => countries.includes(countryName)),
);
